spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update